# Generated by Django 5.2.3 on 2025-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
