# Generated by Django 5.2.3 on 2025-07-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, verbose_name=' Book Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
